---
- name: install node sources
  shell: curl -sL https://deb.nodesource.com/setup_11.x | bash -

- name: install nodejs
  apt:
    name:
      - nodejs
      - npm
    state: present

- name: install yarn
  npm:
    name: yarn
    global: true