---
- name: Install php packages.
  apt:
    name:
      - acl
      - php7.2
      - php7.2-cli
      - php7.2-fpm
      - php7.2-intl
      - php7.2-pdo
      - php7.2-zip
      #- php7.2-xdebug
      - php7.2-xml
      - php7.2-gd
      - php7.2-json
      - php7.2-mysqlnd
      - php7.2-mbstring
      - php7.2-curl
      - curl
    state: present
  notify:
    - restart php-fpm

- name: ensure php.ini settings.
  lineinfile: 
    dest: '/etc/php/7.2/cli/php.ini'
    line: "{{ item.key }}='{{ item.value }}'"
    regexp: "^{{ item.key }}.*$"
  with_dict: "{{ php_ini }}"
  notify:
    - restart php-fpm

- name: ensure php.ini fpm settings.
  lineinfile:
    dest: '/etc/php/7.2/fpm/php.ini'
    line: "{{ item.key }}='{{ item.value }}'"
    regexp: "^{{ item.key }}.*$"
  with_dict: "{{ php_ini }}"
  notify:
    - restart php-fpm

- name: ensure php log dir exists
  file:
    path: "{{ fpm_log_path }}"
    state: directory
    owner: "{{ fpm_user }}"
    group: "{{ fpm_group }}"
    recurse: true

- name: place php-fpm configuration file.
  template:
    src: fpm-www.conf.j2
    dest: /etc/php/7.2/fpm/pool.d/www.conf
  notify:
    - restart php-fpm

- name: start and enable php-fpm service.
  service:
    name: php7.2-fpm
    enabled: true